// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "input": string;
      "wallabag.serverUrl": string;
      "wallabag.clientId": string;
      "wallabag.clientSecret": string;
      "wallabag.username": string;
      "wallabag.password": string;
    };
  }
}
